"""add_system_settings_table

Revision ID: 0f89976b7166
Revises: 9a20437ba741
Create Date: 2026-06-03 17:43:36.081245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f89976b7166'
down_revision: Union[str, Sequence[str], None] = '9a20437ba741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('deger', sa.Text(), nullable=False),
    sa.Column('grup', sa.String(length=50), nullable=False),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('hassas', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_anahtar'), 'system_settings', ['anahtar'], unique=True)
    op.create_index(op.f('ix_system_settings_grup'), 'system_settings', ['grup'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_grup'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_anahtar'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
