"""add_iadeler_table

Revision ID: 6f6668c38987
Revises: 85c524f27a12
Create Date: 2026-05-05 08:47:30.406141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6668c38987'
down_revision: Union[str, Sequence[str], None] = '85c524f27a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iadeler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iade_no', sa.String(length=20), nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sebep_kategori', sa.String(length=50), nullable=False),
    sa.Column('sebep_aciklama', sa.Text(), nullable=False),
    sa.Column('iade_tutari', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('admin_notu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparisler.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iade_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iadeler')
    # ### end Alembic commands ###
