"""initial_tables

Revision ID: 85c524f27a12
Revises: 
Create Date: 2026-04-26 23:57:24.260722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c524f27a12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategoriler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategoriler_slug'), 'kategoriler', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('siparisler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toplam_tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('adres', sa.Text(), nullable=False),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urunler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isim', sa.String(length=255), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('resim_url', sa.String(length=500), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategoriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis_kalemleri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparisler.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siparis_kalemleri')
    op.drop_table('urunler')
    op.drop_table('siparisler')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_kategoriler_slug'), table_name='kategoriler')
    op.drop_table('kategoriler')
    # ### end Alembic commands ###
