"""faz_1_agent_tablolari

Revision ID: 9a20437ba741
Revises: c76d05aa4439
Create Date: 2026-05-16 19:30:44.618724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a20437ba741'
down_revision: Union[str, Sequence[str], None] = 'c76d05aa4439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analitik_ozet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('periyot', sa.String(length=20), nullable=False),
    sa.Column('donem_baslangic', sa.DateTime(timezone=True), nullable=False),
    sa.Column('donem_bitis', sa.DateTime(timezone=True), nullable=False),
    sa.Column('toplam_satis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('siparis_sayisi', sa.Integer(), nullable=False),
    sa.Column('yeni_musteri', sa.Integer(), nullable=False),
    sa.Column('iade_orani', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('top_kategoriler', sa.JSON(), nullable=True),
    sa.Column('top_urunler', sa.JSON(), nullable=True),
    sa.Column('hesaplanma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefing_gecmisi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('icerik', sa.JSON(), nullable=False),
    sa.Column('gonderildi', sa.Boolean(), nullable=False),
    sa.Column('olusturulma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarih')
    )
    op.create_table('agent_konusmalar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('mesajlar', sa.JSON(), nullable=False),
    sa.Column('kanal', sa.String(length=20), nullable=False),
    sa.Column('olusturulma', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('son_aktif', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('kargo_takip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('firma', sa.String(length=50), nullable=True),
    sa.Column('takip_no', sa.String(length=100), nullable=True),
    sa.Column('durum', sa.String(length=50), nullable=True),
    sa.Column('son_konum', sa.Text(), nullable=True),
    sa.Column('gecikme_var', sa.Boolean(), nullable=False),
    sa.Column('guncelleme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparisler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_uyarilari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('esik', sa.Integer(), nullable=False),
    sa.Column('mevcut_stok', sa.Integer(), nullable=False),
    sa.Column('oneri', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=False),
    sa.Column('tetiklenme', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kapatilma', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('siparisler', sa.Column('kargo_no', sa.String(length=100), nullable=True))
    op.add_column('urunler', sa.Column('stok_esigi', sa.Integer(), nullable=True))
    op.execute('UPDATE urunler SET stok_esigi = 10')
    op.alter_column('urunler', 'stok_esigi', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urunler', 'ozellikler')
    op.drop_column('urunler', 'stok_esigi')
    op.drop_constraint(None, 'siparisler', type_='unique')
    op.drop_column('siparisler', 'kargo_no')
    op.drop_table('stok_uyarilari')
    op.drop_table('kargo_takip')
    op.drop_table('agent_konusmalar')
    op.drop_table('briefing_gecmisi')
    op.drop_table('analitik_ozet')
    # ### end Alembic commands ###
