"""add_new_features

Revision ID: c76d05aa4439
Revises: 6f6668c38987
Create Date: 2026-05-09 09:25:13.156706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76d05aa4439'
down_revision: Union[str, Sequence[str], None] = '6f6668c38987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kuponlar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('indirim_tipi', sa.String(length=10), nullable=False),
    sa.Column('deger', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_kullanim', sa.Integer(), nullable=False),
    sa.Column('kullanim_sayisi', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('favoriler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'urun_id', name='uq_user_urun_favori')
    )
    op.create_table('yorumlar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('puan', sa.Integer(), nullable=False),
    sa.Column('yorum', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'urun_id', name='uq_user_urun_yorum')
    )
    op.add_column('siparisler', sa.Column('kupon_kodu', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yorumlar')
    op.drop_table('favoriler')
    op.drop_table('kuponlar')
    op.drop_column('siparisler', 'kupon_kodu')
    # ### end Alembic commands ###
